#Requires AutoHotkey v2.1-alpha.30

#Import "Utils\StringBuilder" { StringBuilder }
#Import "IR\Enum" { Enum }
#Import "Emitters" { EmitEnum }

_Banner := Format("
(
    /**
     * This file is automatically generated and is not meant for manual editing.
     * Changes you make will be lost the next time it is regenerated. 
     * 
     * Generated by AhkBindgen on {1}
     */ 
)", FormatTime(A_Now))

/**
 * Emits code to memory in the form of StringBuilders
 * 
 * @param {Array<String, Type>} registry type registry 
 * @returns {Map<String, StringBuilder>} a map of header file names to emitted code 
 */
export default Emit(registry) {
    global _Banner
    output := Map()

    extracted := registry
        .Values()
        .GroupBy((t) => t.sourceFile)

    for source, types in extracted {
        SplitPath(source, unset, unset, unset, &filename)

        sb := StringBuilder(512)
        sb.AppendLine("#Requires AutoHotkey v2.1-alpha.30").AppendLine()
        sb.AppendRef(&_Banner).AppendRepeat(sb.NewLine, 2)

        for t in types {
            switch true {
                case t is Enum: EmitEnum(t, sb)
                default:
                    continue    ; Don't append a blank line for types we skip
            }
            sb.AppendLine()
        }

    output[filename] := sb
    }

    return output
}