#Requires AutoHotkey v2.1-alpha.30

#Import "Utils\StringBuilder" { StringBuilder }
#Import "IR" as IR
#Import "Emitters" { EmitEnum, EmitStruct, EmitUnion, EmitFunction }

_Banner := Format("
(
    /**
     * This file is automatically generated and is not meant for manual editing.
     * Changes you make will be lost the next time it is regenerated. 
     * 
     * Generated by AhkBindgen on {1}
     */ 
)", FormatTime(A_Now))

/**
 * Emits code to memory in the form of StringBuilders
 * 
 * @param {Array<String, Type>} registry type registry 
 * @returns {Map<String, StringBuilder>} a map of header file names to emitted code 
 */
export default Emit(registry, dll) {
    global _Banner
    output := Map()

    extracted := registry
        .Values()
        .GroupBy((t) => t.sourceFile)

    for source, types in extracted {
        SplitPath(source, , , , &filename)

        sb := StringBuilder(512)
        sb.AppendLine("#Requires AutoHotkey v2.1-alpha.30").AppendLine()
        sb.AppendRef(&_Banner).AppendRepeat(sb.NewLine, 2)

        for t in types {
            switch true {
                case t is IR.Enum.Enum:
                    EmitEnum(t, sb)
                case t is IR.Struct.Struct:
                    EmitStruct(t, registry, sb)
                case t is IR.Struct.Union:
                    EmitUnion(t, registry, sb)
                case t is IR.Function.Function:
                    EmitFunction(t, dll, registry, sb)
                default:
                    continue    ; Don't append a blank line for types we skip
            }
            sb.AppendLine()
        }

        output[filename] := sb
    }

    return output
}