#Requires AutoHotkey v2.1-alpha.30

#Import "Utils\StringBuilder" { StringBuilder }
#Import "IR" as IR
#Import "IR\Walk" { WalkTypeRefs, DeclTypes}
#Import "Emitters" { EmitEnum, EmitStruct, EmitUnion, EmitFunction, EmitTypedef }

_Banner := Format("
(
    /**
     * This file is automatically generated and is not meant for manual editing.
     * Changes you make will be lost the next time it is regenerated. 
     * 
     * Generated by AhkBindgen on {1}
     */ 
)", FormatTime(A_Now))

/**
 * Emits code to memory in the form of StringBuilders
 * 
 * @param {Array<String, Type>} registry type registry 
 * @returns {Map<String, StringBuilder>} a map of header file names to emitted code 
 */
export default Emit(registry, dll) {
    global _Banner
    output := Map()

    extracted := registry
        .Values()
        .GroupBy((t) => t.sourceFile)

    for source, types in extracted {
        SplitPath(source, , , , &filename)

        sb := StringBuilder(512)
        sb.AppendLine("#Requires AutoHotkey v2.1-alpha.30").AppendLine()

        EmitImports(types, filename, registry, sb)

        sb.AppendRef(&_Banner).AppendRepeat(sb.NewLine, 2)

        for t in types {
            switch true {
                case t is IR.Enum.Enum:
                    EmitEnum(t, sb)
                case t is IR.Struct.Struct:
                    EmitStruct(t, registry, sb)
                case t is IR.Struct.Union:
                    EmitUnion(t, registry, sb)
                case t is IR.Function.Function:
                    EmitFunction(t, dll, registry, sb)
                case t is IR.Type.EmittableTypedef:
                    EmitTypedef(t, registry, sb)
                default:
                    continue    ; Don't append a blank line for types we skip
            }
            sb.AppendLine()
        }

        output[filename] := sb
    }

    return output
}

/**
 * Collect the declarations referenced by `types` that live in *other* output files and emit a granular
 * `#Import "<file>" { Name, ... }` line for each such file into `sb`. Only types actually used are imported;
 * self-references and references that don't resolve to a registered declaration are skipped.
 *
 * @param {Array<Emittable>} types the declarations being emitted into the current file
 * @param {String} filename the current output file's basename (without extension)
 * @param {Map<String, Emittable>} registry the type registry, keyed by USR
 * @param {StringBuilder} sb StringBuilder to emit the imports into
 * @returns {void}
 */
EmitImports(types, filename, registry, sb) {
    refs := Map()   ; used as a set of referenced USRs
    for t in types {
        CollectRefs(t, refs, registry)
    }

    imports := Map()    ; targetFile (basename) -> Map used as a set of exported names
    imports.CaseSense := false
    for usr in refs {
        if !registry.Has(usr)
            continue    ; reference to a type from a header we didn't parse; nothing to import

        target := registry[usr]
        SplitPath(target.sourceFile, , , , &targetFile)
        if targetFile = filename
            continue    ; same file - no import needed

        imports.GetOrAdd(targetFile, Map())[target.name] := true
    }

    if !imports.Count
        return

    for targetFile in imports.Keys().Sorted((a, b) => StrCompare(a, b)) {
        names := imports[targetFile].Keys().Sorted((a, b) => StrCompare(a, b))
        sb.AppendLine('#Import "' targetFile '" { ' String.Join(", ", names*) ' }')
    }
    sb.AppendLine()
}

/**
 * Add the USRs of every cross-file-referenceable type used by `decl` into the `refs` set. Mirrors which
 * references survive into `ToSpecifier()` output.
 *
 * @param {Emittable} decl the declaration to inspect
 * @param {Map} refs set of referenced USRs to populate
 * @param {Map<String, Emittable>} registry the type registry, keyed by USR
 * @returns {void}
 */
CollectRefs(decl, refs, registry) {
    for refType in DeclTypes(decl) {
        WalkTypeRefs(refType,
            (named) => refs[named.usr] := true,
            ; Only include resolveable library typedefs. System typedefs are collapsed to their underlying
            ; primitives, and anonymous typedefs aren't emitted, so in that case fall back to the underlying record
            (td, recurse) => (!td.isSystem && registry.Has(td.usr)) ? (refs[td.usr] := true) : recurse())
    }
}